### ISSUE TITLE
Модель Client должна соответствовать тз

### ISSUE THREAD

**Issue by AlexeyBerezhnoy** [SweetKitt/Parking#5]
[ ] Для поля name должно быть минимальная длина 3 символа максимальная неограничена. Поле в Django без ограничения по длине https://docs.djangoproject.com/en/4.0/ref/models/fields/#textfield . Для ограничения минимальной длины следует задать валидатор https://docs.djangoproject.com/en/4.0/ref/models/fields/#validators
[ ] Для phone не должно быть максимального ограничения длины по этому снова сюда подойдет поле TextField. Проверку на уникальность должно обеспечить свойство https://docs.djangoproject.com/en/4.0/ref/models/fields/#unique
[ ] Для поля address использовать TextField по той же причине.

**Comment by SweetKitt** [comment]
name = models.TextField('ФИО', validators=[MinLengthValidator(3, message='Имя не может быть меньше 3х символов')])

Сотворила вот такую фигню для контроля мин длины. И вроде да, не записывает пользователя с именем короче 3х символов, но и ошибку не выдает, когда нажимаешь сохранить. Просто обновляется страница и ничего не происходит, хотя я надеялась, что указав "message" будет показываться ошибка.
