### ISSUE TITLE
Неправильная связь между клиентом и автомобилем

### ISSUE THREAD

**Issue by AlexeyBerezhnoy** [SweetKitt/Parking#9]
Согласно тз у клиента может быть несколько автомобилей. Сейчас же в коде у каждого клиента есть ForeignKey на автомобиль. Это неправильно. Так получается что у одного клиента только один автомобиль(
Раньше было правильно, у каждого автомобиля был ForeignKey на владельца. Верни как было.

**Comment by SweetKitt** [comment]
можно сделать многие ко многим (ManyToManyField) и логически это будет корректно. У клиента может быть много автомобилей, так же как и у автомобиля много владельцев. Не так ли?  
Я все начала менять, так как в ТЗ у сущности "Клиента" есть атрибут "Автомобил(ь/и)(обязательный, мин 1)" и глупо из этого атрибута делать простой счетчик ни к чему не подвязанный( хотя и тогда я проекте думала,что можно как-то сделать отслеживатель).

**Comment by AlexeyBerezhnoy** [comment]
В тз ничего не написано что у автомобиля может несколько владельцев. И это не совсем логично, типа два челика, поставили на парковку одну и туже тачку.
Атрибут Автомобил(ь/и) это не счётчик это как раз связь с автомобилями.
У владельца появится связь на все его автомобили, когда ты добавишь ForeignKey автомобилю на владельца.
Если у нас будет такой код
```
class Car(models.Model):
    owner = models.ForeignKey(Client, on_delete=models.CASCADE)
```
То мы можем использовать обратную связь

```
client = Client.objects.first()
client.car_set.all()  # получить все автомобили челика
client.car_set.add(Car())  # добавить челу новую тачку
```
Вот документация по обратной связи https://docs.djangoproject.com/en/4.1/topics/db/queries/#backwards-related-objects
В целом всю документацию еще раз почитай, будет полезно

**Comment by SweetKitt** [comment]
*нецензурная брань*
